### ISSUE TITLE
Use a datamodel instead of String[]

### ISSUE THREAD

**Issue by orangepaydev** [nurzulaikhaz/java#1]
https://github.com/nurzulaikhaz/java/blob/518534b91479b79ed468bca39508c86885b4e1d6/src/main/java/org/example/biz/DataBiz.java#L7

String[] is not a good data model, as we add more fields then we'll be referencing the index via the raw position.  Could we have a model class so that the responsibility of parsing the fields are done in 1 component.

**Comment by nurzulaikhaz** [comment]
I have created model class Person to replace String[]
