### ISSUE TITLE
FileUtil should just be a Util class

### ISSUE THREAD

**Issue by orangepaydev** [nurzulaikhaz/java#2]
https://github.com/nurzulaikhaz/java/blob/518534b91479b79ed468bca39508c86885b4e1d6/src/main/java/org/example/utils/FileUtil.java#L11

FileUtil as the name suggest should just be a utility class.  It's now mixing both business logic and util into a single class.

**Comment by nurzulaikhaz** [comment]
I've updated and removed the business logic in the util class
